/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LivraisonsRouteImport } from './routes/livraisons'
import { Route as FacturesRouteImport } from './routes/factures'
import { Route as ConteneursRouteImport } from './routes/conteneurs'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as AlertesRouteImport } from './routes/alertes'
import { Route as IndexRouteImport } from './routes/index'

const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonsRoute = LivraisonsRouteImport.update({
  id: '/livraisons',
  path: '/livraisons',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesRoute = FacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteneursRoute = ConteneursRouteImport.update({
  id: '/conteneurs',
  path: '/conteneurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertesRoute = AlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertes': typeof AlertesRoute
  '/carte': typeof CarteRoute
  '/clients': typeof ClientsRoute
  '/conteneurs': typeof ConteneursRoute
  '/factures': typeof FacturesRoute
  '/livraisons': typeof LivraisonsRoute
  '/messages': typeof MessagesRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertes': typeof AlertesRoute
  '/carte': typeof CarteRoute
  '/clients': typeof ClientsRoute
  '/conteneurs': typeof ConteneursRoute
  '/factures': typeof FacturesRoute
  '/livraisons': typeof LivraisonsRoute
  '/messages': typeof MessagesRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertes': typeof AlertesRoute
  '/carte': typeof CarteRoute
  '/clients': typeof ClientsRoute
  '/conteneurs': typeof ConteneursRoute
  '/factures': typeof FacturesRoute
  '/livraisons': typeof LivraisonsRoute
  '/messages': typeof MessagesRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertes'
    | '/carte'
    | '/clients'
    | '/conteneurs'
    | '/factures'
    | '/livraisons'
    | '/messages'
    | '/parametres'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertes'
    | '/carte'
    | '/clients'
    | '/conteneurs'
    | '/factures'
    | '/livraisons'
    | '/messages'
    | '/parametres'
  id:
    | '__root__'
    | '/'
    | '/alertes'
    | '/carte'
    | '/clients'
    | '/conteneurs'
    | '/factures'
    | '/livraisons'
    | '/messages'
    | '/parametres'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertesRoute: typeof AlertesRoute
  CarteRoute: typeof CarteRoute
  ClientsRoute: typeof ClientsRoute
  ConteneursRoute: typeof ConteneursRoute
  FacturesRoute: typeof FacturesRoute
  LivraisonsRoute: typeof LivraisonsRoute
  MessagesRoute: typeof MessagesRoute
  ParametresRoute: typeof ParametresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraisons': {
      id: '/livraisons'
      path: '/livraisons'
      fullPath: '/livraisons'
      preLoaderRoute: typeof LivraisonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures': {
      id: '/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof FacturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteneurs': {
      id: '/conteneurs'
      path: '/conteneurs'
      fullPath: '/conteneurs'
      preLoaderRoute: typeof ConteneursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertes': {
      id: '/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertesRoute: AlertesRoute,
  CarteRoute: CarteRoute,
  ClientsRoute: ClientsRoute,
  ConteneursRoute: ConteneursRoute,
  FacturesRoute: FacturesRoute,
  LivraisonsRoute: LivraisonsRoute,
  MessagesRoute: MessagesRoute,
  ParametresRoute: ParametresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
